mockQuestions = [
  {
    chapterId: "615c1d1f9b9f410001c7b5e1",
    text: "What is the capital of France?",
    choices: ["Paris", "Rome", "Berlin"],
    correctAnswer: "Paris",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b5e1",
    text: "What is the square root of 64?",
    choices: ["6", "8", "10"],
    correctAnswer: "8",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b5e1",
    text: "Which gas do plants absorb from the atmosphere?",
    choices: ["Oxygen", "Carbon Dioxide", "Nitrogen"],
    correctAnswer: "Carbon Dioxide",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b5e1",
    text: "Who developed the theory of relativity?",
    choices: ["Newton", "Einstein", "Galileo"],
    correctAnswer: "Einstein",
    difficulty: "difficult",
    objective: "understanding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b5e1",
    text: "Which element has the chemical symbol 'O'?",
    choices: ["Oxygen", "Osmium", "Oganesson"],
    correctAnswer: "Oxygen",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b5e6",
    text: "How do you calculate the area of a circle?",
    choices: ["πr²", "2πr", "r²/π"],
    correctAnswer: "πr²",
    difficulty: "difficult",
    objective: "creativity",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b5e6",
    text: "Which programming language is primarily used for web development?",
    choices: ["Python", "JavaScript", "C++"],
    correctAnswer: "JavaScript",
    difficulty: "simple",
    objective: "understanding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b5e6",
    text: "Which planet is known as the Red Planet?",
    choices: ["Earth", "Mars", "Jupiter"],
    correctAnswer: "Mars",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b5e6",
    text: "What is the chemical formula for water?",
    choices: ["H2O", "CO2", "O2"],
    correctAnswer: "H2O",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b5ea",
    text: "How does photosynthesis work?",
    choices: [
      "Plants convert sunlight into energy",
      "Plants absorb nutrients from the soil",
      "Plants release oxygen by consuming nitrogen",
    ],
    correctAnswer: "Plants convert sunlight into energy",
    difficulty: "difficult",
    objective: "understanding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b5ea",
    text: "Solve the equation: 3x + 2 = 11",
    choices: ["x = 1", "x = 3", "x = 9"],
    correctAnswer: "x = 3",
    difficulty: "difficult",
    objective: "creativity",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b5ea",
    text: "What is the powerhouse of the cell?",
    choices: ["Nucleus", "Mitochondria", "Chloroplast"],
    correctAnswer: "Mitochondria",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b5ed",
    text: "Explain how quantum computing works.",
    choices: [
      "Quantum bits store information in two states at once",
      "Regular bits store information as binary",
      "Classical computing algorithms are linear",
    ],
    correctAnswer: "Quantum bits store information in two states at once",
    difficulty: "difficult",
    objective: "creativity",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b5ed",
    text: "In what year did the French Revolution begin?",
    choices: ["1776", "1789", "1799"],
    correctAnswer: "1789",
    difficulty: "difficult",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b5ed",
    text: "What is the first law of thermodynamics?",
    choices: [
      "Energy cannot be created or destroyed",
      "Entropy always increases",
      "For every action, there's an equal and opposite reaction",
    ],
    correctAnswer: "Energy cannot be created or destroyed",
    difficulty: "difficult",
    objective: "understanding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b5ed",
    text: "What is the chemical formula of methane?",
    choices: ["CH4", "C2H6", "CO2"],
    correctAnswer: "CH4",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b5ed",
    text: "Who wrote the novel '1984'?",
    choices: ["George Orwell", "Aldous Huxley", "J.K. Rowling"],
    correctAnswer: "George Orwell",
    difficulty: "simple",
    objective: "understanding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b5ed",
    text: "Which element is represented by the symbol 'Fe'?",
    choices: ["Iron", "Lead", "Gold"],
    correctAnswer: "Iron",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b5ed",
    text: "What is the main theme of Shakespeare's 'Hamlet'?",
    choices: ["Revenge", "Love", "Betrayal"],
    correctAnswer: "Revenge",
    difficulty: "difficult",
    objective: "understanding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b5ed",
    text: "How do you calculate the derivative of a function?",
    choices: [
      "Use limits to find the slope of the curve",
      "Use integration to calculate area",
      "Use matrices to find the solution",
    ],
    correctAnswer: "Use limits to find the slope of the curve",
    difficulty: "difficult",
    objective: "creativity",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b5ed",
    text: "What is the largest planet in our solar system?",
    choices: ["Earth", "Jupiter", "Saturn"],
    correctAnswer: "Jupiter",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b5ed",
    text: "What is the chemical symbol for gold?",
    choices: ["Au", "Ag", "Pb"],
    correctAnswer: "Au",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b5ed",
    text: "Who proposed the theory of evolution by natural selection?",
    choices: ["Charles Darwin", "Isaac Newton", "Albert Einstein"],
    correctAnswer: "Charles Darwin",
    difficulty: "simple",
    objective: "understanding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b603",
    text: "What is the integral of x^2?",
    choices: ["x^3/3 + C", "2x + C", "1/x + C"],
    correctAnswer: "x^3/3 + C",
    difficulty: "difficult",
    objective: "creativity",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b603",
    text: "Which ancient civilization built the pyramids?",
    choices: ["Romans", "Greeks", "Egyptians"],
    correctAnswer: "Egyptians",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b603",
    text: "What is the speed of light in a vacuum?",
    choices: ["3.00 × 10^8 m/s", "1.50 × 10^8 m/s", "2.00 × 10^8 m/s"],
    correctAnswer: "3.00 × 10^8 m/s",
    difficulty: "difficult",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b603",
    text: "Which of the following is a renewable energy source?",
    choices: ["Coal", "Natural Gas", "Solar Power"],
    correctAnswer: "Solar Power",
    difficulty: "simple",
    objective: "understanding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b603",
    text: "Which programming paradigm focuses on objects and classes?",
    choices: [
      "Functional Programming",
      "Object-Oriented Programming",
      "Procedural Programming",
    ],
    correctAnswer: "Object-Oriented Programming",
    difficulty: "difficult",
    objective: "understanding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b603",
    text: "Who wrote 'The Odyssey'?",
    choices: ["Homer", "Shakespeare", "Virgil"],
    correctAnswer: "Homer",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b603",
    text: "What is the equation of a straight line?",
    choices: ["y = mx + b", "x = my + b", "y = mx"],
    correctAnswer: "y = mx + b",
    difficulty: "simple",
    objective: "understanding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b603",
    text: "Which organ in the human body is primarily responsible for filtering blood?",
    choices: ["Liver", "Heart", "Kidneys"],
    correctAnswer: "Kidneys",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b603",
    text: "What is the derivative of sin(x)?",
    choices: ["cos(x)", "-cos(x)", "sin(x)"],
    correctAnswer: "cos(x)",
    difficulty: "difficult",
    objective: "creativity",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b603",
    text: "Which of the following is an example of a noble gas?",
    choices: ["Oxygen", "Neon", "Nitrogen"],
    correctAnswer: "Neon",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b60d",
    text: "Which mathematical concept is used to calculate probabilities?",
    choices: ["Calculus", "Algebra", "Statistics"],
    correctAnswer: "Statistics",
    difficulty: "difficult",
    objective: "understanding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b60d",
    text: "What is the powerhouse of the cell?",
    choices: ["Nucleus", "Mitochondria", "Ribosome"],
    correctAnswer: "Mitochondria",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b60d",
    text: "What is the result of 15 + 25?",
    choices: ["30", "40", "50"],
    correctAnswer: "40",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b60d",
    text: "Which of the following is a function of the heart?",
    choices: ["Pumping blood", "Digesting food", "Filtering waste"],
    correctAnswer: "Pumping blood",
    difficulty: "simple",
    objective: "understanding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b60d",
    text: "How many continents are there?",
    choices: ["5", "6", "7"],
    correctAnswer: "7",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b60d",
    text: "Who painted the Mona Lisa?",
    choices: ["Vincent Van Gogh", "Leonardo da Vinci", "Pablo Picasso"],
    correctAnswer: "Leonardo da Vinci",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b613",
    text: "What is the circumference of a circle with radius r?",
    choices: ["2πr", "πr^2", "r^2"],
    correctAnswer: "2πr",
    difficulty: "difficult",
    objective: "creativity",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b613",
    text: "Which element has the atomic number 6?",
    choices: ["Carbon", "Oxygen", "Hydrogen"],
    correctAnswer: "Carbon",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b613",
    text: "What is the process by which plants make their food?",
    choices: ["Respiration", "Photosynthesis", "Transpiration"],
    correctAnswer: "Photosynthesis",
    difficulty: "simple",
    objective: "understanding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b613",
    text: "Which country is the largest by land area?",
    choices: ["Russia", "Canada", "China"],
    correctAnswer: "Russia",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b613",
    text: "What is the acceleration due to gravity on Earth?",
    choices: ["9.8 m/s^2", "8.9 m/s^2", "10.1 m/s^2"],
    correctAnswer: "9.8 m/s^2",
    difficulty: "difficult",
    objective: "understanding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b613",
    text: "Who wrote 'Pride and Prejudice'?",
    choices: ["Emily Brontë", "Jane Austen", "Mary Shelley"],
    correctAnswer: "Jane Austen",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b613",
    text: "What is the Pythagorean Theorem?",
    choices: ["a^2 + b^2 = c^2", "a^2 - b^2 = c^2", "a^2 / b^2 = c^2"],
    correctAnswer: "a^2 + b^2 = c^2",
    difficulty: "difficult",
    objective: "understanding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b613",
    text: "Which planet is known as the Red Planet?",
    choices: ["Earth", "Venus", "Mars"],
    correctAnswer: "Mars",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b613",
    text: "What is the chemical formula of water?",
    choices: ["H2O", "O2", "CO2"],
    correctAnswer: "H2O",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "615c1d1f9b9f410001c7b613",
    text: "What is the square root of 81?",
    choices: ["7", "9", "8"],
    correctAnswer: "9",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "616c1e2b9f1b410002d7b609",
    text: "Which ocean is the largest?",
    choices: ["Atlantic", "Indian", "Pacific"],
    correctAnswer: "Pacific",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "616c1e2b9f1b410002d7b609",
    text: "What is the derivative of cos(x)?",
    choices: ["-sin(x)", "sin(x)", "cos(x)"],
    correctAnswer: "-sin(x)",
    difficulty: "difficult",
    objective: "creativity",
  },
  {
    chapterId: "616c1e2b9f1b410002d7b609",
    text: "What is the capital of Australia?",
    choices: ["Sydney", "Melbourne", "Canberra"],
    correctAnswer: "Canberra",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "616c1e2b9f1b410002d7b609",
    text: "Which gas do plants absorb from the atmosphere?",
    choices: ["Oxygen", "Carbon Dioxide", "Nitrogen"],
    correctAnswer: "Carbon Dioxide",
    difficulty: "simple",
    objective: "understanding",
  },
  {
    chapterId: "616c1e2b9f1b410002d7b609",
    text: "What is the square of 12?",
    choices: ["144", "122", "100"],
    correctAnswer: "144",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "616c1e2b9f1b410002d7b609",
    text: "Who painted the ceiling of the Sistine Chapel?",
    choices: ["Michelangelo", "Leonardo da Vinci", "Raphael"],
    correctAnswer: "Michelangelo",
    difficulty: "simple",
    objective: "reminding",
  },
  {
    chapterId: "616c1e2b9f1b410002d7b609",
    text: "Which is the most abundant gas in the Earth's atmosphere?",
    choices: ["Oxygen", "Carbon Dioxide", "Nitrogen"],
    correctAnswer: "Nitrogen",
    difficulty: "difficult",
    objective: "reminding",
  },
  {
    chapterId: "616c1e2b9f1b410002d7b609",
    text: "What is the boiling point of water at sea level?",
    choices: ["100°C", "90°C", "80°C"],
    correctAnswer: "100°C",
    difficulty: "simple",
    objective: "understanding",
  },
  {
    chapterId: "616c1e2b9f1b410002d7b611",
    text: "What is the formula for calculating the area of a circle?",
    choices: ["πr^2", "2πr", "r^2"],
    correctAnswer: "πr^2",
    difficulty: "difficult",
    objective: "creativity",
  },
  {
    chapterId: "616c1e2b9f1b410002d7b611",
    text: "Who discovered penicillin?",
    choices: ["Alexander Fleming", "Marie Curie", "Louis Pasteur"],
    correctAnswer: "Alexander Fleming",
    difficulty: "difficult",
    objective: "reminding",
  },
  {
    chapterId: "616c1e2b9f1b410002d7b611",
    text: "Which country hosted the 2016 Summer Olympics?",
    choices: ["Japan", "Brazil", "USA"],
    correctAnswer: "Brazil",
    difficulty: "simple",
    objective: "reminding",
  },
];

module.exports = mockQuestions